//
//  ScreenDeckSmokeTests+Screens.swift
//  DialedInUITests
//
//  Generated by scripts/gen-smoke-tests.sh from AppViewForUITesting.swift. Do not edit.
//

import XCTest

extension ScreenDeckSmokeTests {

    func testCreateExercise() { smoke("STARTSCREEN_CREATE_EXERCISE") }

    func testCreateWorkout() { smoke("STARTSCREEN_CREATE_WORKOUT") }

    func testCreateProgram() { smoke("STARTSCREEN_CREATE_PROGRAM") }

    func testSocialProfile() { smoke("STARTSCREEN_SOCIAL_PROFILE") }

    func testComments() { smoke("STARTSCREEN_COMMENTS") }

    func testOwnProfile() { smoke("STARTSCREEN_OWN_PROFILE") }

    func testNotifications() { smoke("STARTSCREEN_NOTIFICATIONS") }

    func testUsername() { smoke("STARTSCREEN_USERNAME") }

    func testSharedItem() { smoke("STARTSCREEN_SHARED_ITEM") }

    func testShareCard() { smoke("STARTSCREEN_SHARE_CARD") }

    func testDashboard() { smoke("STARTSCREEN_DASHBOARD") }

    func testTraining() { smoke("STARTSCREEN_TRAINING") }

    func testWorkoutTracker() { smoke("STARTSCREEN_WORKOUT_TRACKER") }

    func testTemplateDetail() { smoke("STARTSCREEN_TEMPLATE_DETAIL") }

    func testProgramLibrary() { smoke("STARTSCREEN_PROGRAM_LIBRARY") }

    func testActiveProgram() { smoke("STARTSCREEN_ACTIVE_PROGRAM") }

    func testExerciseDetail() { smoke("STARTSCREEN_EXERCISE_DETAIL") }

    func testExercises() { smoke("STARTSCREEN_EXERCISES") }

    func testWorkoutHistory() { smoke("STARTSCREEN_WORKOUT_HISTORY") }

    func testSessionDetail() { smoke("STARTSCREEN_SESSION_DETAIL") }

    func testGymProfiles() { smoke("STARTSCREEN_GYM_PROFILES") }

    func testNutrition() { smoke("STARTSCREEN_NUTRITION") }

    func testMealDetail() { smoke("STARTSCREEN_MEAL_DETAIL") }

    func testRecipes() { smoke("STARTSCREEN_RECIPES") }

    func testRecipeDetail() { smoke("STARTSCREEN_RECIPE_DETAIL") }

    func testFoods() { smoke("STARTSCREEN_FOODS") }

    func testFoodDetail() { smoke("STARTSCREEN_FOOD_DETAIL") }

    func testAnalytics() { smoke("STARTSCREEN_ANALYTICS") }

    func testBodyMetrics() { smoke("STARTSCREEN_BODY_METRICS") }

    func testScaleWeight() { smoke("STARTSCREEN_SCALE_WEIGHT") }

    func testMeasurementDetail() { smoke("STARTSCREEN_MEASUREMENT_DETAIL") }

    func testProfile() { smoke("STARTSCREEN_PROFILE") }

    func testAccount() { smoke("STARTSCREEN_ACCOUNT") }

    func testSearch() { smoke("STARTSCREEN_SEARCH") }

    func testFollowers() { smoke("STARTSCREEN_FOLLOWERS") }

    func testInvite() { smoke("STARTSCREEN_INVITE") }

    func testSetKeyboard() { smoke("STARTSCREEN_SET_KEYBOARD") }

    func testWeeklyReview() { smoke("STARTSCREEN_WEEKLY_REVIEW") }

    func testChallengeDetail() { smoke("STARTSCREEN_CHALLENGE_DETAIL") }

    func testChallenges() { smoke("STARTSCREEN_CHALLENGES") }
}
