#!/usr/bin/env bash
# Regenerates DialedInUITests/ScreenDeckSmokeTests+Screens.swift: one smoke test per
# STARTSCREEN_* argument in AppViewForUITesting.swift. Run after adding a start screen.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOURCE="$ROOT/DialedIn/Root/EntryPoints/AppViewForUITesting.swift"
OUT="$ROOT/DialedInUITests/ScreenDeckSmokeTests+Screens.swift"

{
    echo "//"
    echo "//  ScreenDeckSmokeTests+Screens.swift"
    echo "//  DialedInUITests"
    echo "//"
    echo "//  Generated by scripts/gen-smoke-tests.sh from AppViewForUITesting.swift. Do not edit."
    echo "//"
    echo
    echo "import XCTest"
    echo
    echo "extension ScreenDeckSmokeTests {"
    grep -o '"STARTSCREEN_[A-Z0-9_]*"' "$SOURCE" | tr -d '"' | awk '!seen[$0]++' | while read -r arg; do
        # STARTSCREEN_CHALLENGE_DETAIL -> ChallengeDetail
        name=$(echo "${arg#STARTSCREEN_}" | awk -F_ '{ for (i = 1; i <= NF; i++) printf "%s%s", substr($i, 1, 1), tolower(substr($i, 2)) }')
        echo
        echo "    func test${name}() { smoke(\"$arg\") }"
    done
    echo "}"
} > "$OUT"
echo "Wrote $(grep -c 'func test' "$OUT") tests to $OUT"
